language: node_js
node_js: node

script:
    - npm run listdiff
    - npm run lint
    - if [ "$TRAVIS_TAG" ]; then make deploy; else make build; fi

before_deploy:
    - touch ./build/.nojekyll

deploy:
    - provider: npm
      edge: true
      on:
          repo: magic-akari/lrc-maker
          branch: master
          tags: true

    - provider: pages
      edge: true
      local_dir: build
      on:
          branch: master

    - provider: pages
      edge: true
      local_dir: build
      repo: lrc-maker/lrc-maker.github.io
      target_branch: master
      on:
          repo: magic-akari/lrc-maker
          branch: master
          tags: true
